name: "构建和发布"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-latest
            target: darwin-universal
          - name: ubuntu-latest
            target: linux-x86_64
          - name: windows-latest
            target: windows-x86_64

    runs-on: ${{ matrix.platform.name }}
    
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: 安装系统依赖 (Ubuntu)
        if: matrix.platform.name == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: 安装依赖
        run: yarn

      - name: 添加执行权限到构建脚本 (非 Windows)
        if: matrix.platform.name != 'windows-latest'
        run: chmod +x ./ci/build.sh

      - name: 构建应用 (非 Windows)
        if: matrix.platform.name != 'windows-latest'
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: ./ci/build.sh

      - name: 构建应用 (Windows)
        if: matrix.platform.name == 'windows-latest'
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: |
          if (-not [string]::IsNullOrEmpty($env:TAURI_SIGNING_PRIVATE_KEY)) {
            Write-Host "已设置 TAURI_SIGNING_PRIVATE_KEY"
          } else {
            Write-Host "警告: TAURI_SIGNING_PRIVATE_KEY 环境变量未设置，将禁用自动更新功能"
            jq 'del(.plugins.updater) | del(.bundle.createUpdaterArtifacts)' src-tauri/tauri.conf.json > temp.json
            Move-Item -Path temp.json -Destination src-tauri/tauri.conf.json -Force
          }
          
          yarn tauri build

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: easy-todo-${{ matrix.platform.target }}
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/nsis/*.exe
            latest.json
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 下载所有构建产物
        uses: actions/download-artifact@v3
        
      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            easy-todo-*/src-tauri/target/release/bundle/dmg/*.dmg
            easy-todo-*/src-tauri/target/release/bundle/appimage/*.AppImage
            easy-todo-*/src-tauri/target/release/bundle/nsis/*.exe
            easy-todo-*/latest.json
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 