name: 发布应用

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    name: 构建并发布 (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      
      - name: 安装Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: 缓存Rust依赖
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"
      
      - name: 安装Linux依赖
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: 安装Yarn
        run: npm install -g yarn
      
      - name: 安装前端依赖
        run: yarn install
      
      - name: 前端代码构建
        run: yarn build
      
      - name: 编译并打包
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Easy Todo v${{ github.ref_name }}"
          releaseBody: "完整更新日志请查看 CHANGELOG.md"
          releaseDraft: false
          prerelease: false 