name: Rust Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src-tauri/**'
      - '.github/workflows/rust-test.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'src-tauri/**'
      - '.github/workflows/rust-test.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Rust Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 安装Rust工具链
      uses: dtolnay/rust-toolchain@stable
    
    - name: 缓存Rust依赖
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "src-tauri -> target"
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    
    - name: 检查代码格式
      working-directory: ./src-tauri
      run: cargo fmt --check
    
    - name: 运行Clippy代码分析
      working-directory: ./src-tauri
      run: cargo clippy -- -D warnings
    
    - name: 运行单元测试
      working-directory: ./src-tauri
      run: cargo test 